[env:esp32-s3-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_16mb.csv
board_build.filesystem = littlefs

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -DASYNCWEBSERVER_USE_MUTEX=1

lib_deps =
    ESP32Async/AsyncTCP @ 3.5.0
    ESP32Async/ESPAsyncWebServer @ 3.12.0
    bblanchon/ArduinoJson

extra_scripts = pre:scripts/check_web_assets.py
